# Generated by Django 5.0.2 on 2024-03-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_alter_institucion_options_alter_posicion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goleador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('goles', models.IntegerField()),
            ],
        ),
    ]
